#!/usr/bin/env bash
#
# Senderrr — cross-compile the Node.js runtime as libnode.so for Android.
#
# Produces the shared library the Android app's JNI bridge loads and calls
# node::Start() on (PRD docs/23-android-ndk-migration-prd.md, ADR-3), plus the
# headers that bridge compiles against.
#
# Why this recipe: upstream Node's own --dest-os=android support, invoked the
# way Node's bundled android_configure.py does it, with --shared added so the
# build emits libnode.so instead of a `node` executable. This is the same path
# Termux's nodejs-lts package uses; nodejs-mobile is not an option because it
# still tracks Node 18 and NestJS 11 needs >= 20.
#
# This half runs on Linux only, inside the toolchain image. Run
# scripts/build-libnode.sh instead — it is the entry point, and it drives this.

set -euo pipefail

# ── Pins (§10 — pin versions deliberately, know why) ────────────────────────
# Node: latest 24.x LTS ("Krypton"). Termux's nodejs-lts reference recipe was
# on 24.18.0 when the PRD was written; same line, same configure surface.
readonly NODE_VERSION="24.20.0"
# NDK: the r28 LTS already installed with this project's Android SDK.
readonly NDK_VERSION="28.2.13676358"
# API 28 (Android 9) — chosen so we skip the aligned_alloc=memalign shim that
# Termux only needs below 28 (PRD ADR-3, commit 6's minSdk).
readonly ANDROID_API="28"

readonly ANDROID_ABI="${ANDROID_ABI:-arm64-v8a}"

# ── Output helpers ──────────────────────────────────────────────────────────
readonly GREEN='\033[0;32m' RED='\033[0;31m' BLUE='\033[0;34m' BOLD='\033[1m' NC='\033[0m'
log_info()    { echo -e "${BLUE}i${NC} $1"; }
log_success() { echo -e "${GREEN}v${NC} $1"; }
log_error()   { echo -e "${RED}x${NC} $1" >&2; }
log_step()    { echo -e "\n${BOLD}-- $1 --${NC}"; }
die()         { log_error "$1"; exit 1; }

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
readonly BUILD_DIR="$PROJECT_DIR/.ndk-build"
readonly SOURCE_DIR="$BUILD_DIR/node-v$NODE_VERSION"
readonly JNI_LIBS_DIR="$PROJECT_DIR/android/app/src/main/jniLibs/$ANDROID_ABI"
readonly HEADERS_DIR="$PROJECT_DIR/android/app/src/main/cpp/nodeheaders"

CLEAN_BUILD=0
[ "${1:-}" = "--clean" ] && CLEAN_BUILD=1

# ── ABI -> the three names Node, V8 and the NDK each use for it ─────────────
case "$ANDROID_ABI" in
  arm64-v8a)   DEST_CPU="arm64"; TOOLCHAIN_PREFIX="aarch64-linux-android" ;;
  armeabi-v7a) DEST_CPU="arm";   TOOLCHAIN_PREFIX="armv7a-linux-androideabi" ;;
  x86_64)      DEST_CPU="x64";   TOOLCHAIN_PREFIX="x86_64-linux-android" ;;
  *) die "Unsupported ANDROID_ABI '$ANDROID_ABI' (arm64-v8a, armeabi-v7a, x86_64)." ;;
esac
# V8 and gyp spell arm64 as "arm64" and x86_64 as "x64", matching DEST_CPU.
readonly GYP_ARCH="$DEST_CPU"

# ── Locate the NDK ──────────────────────────────────────────────────────────
find_ndk_root() {
  local sdk_root="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$HOME/Library/Android/sdk}}"
  local candidate="$sdk_root/ndk/$NDK_VERSION"
  [ -d "$candidate" ] || die "NDK $NDK_VERSION not found at $candidate.
It should have been baked into the toolchain image by
scripts/libnode-builder.Dockerfile — rebuild the image with --no-cache."
  echo "$candidate"
}

# gyp builds V8's own tools (mksnapshot, torque) for the machine doing the
# build, using GNU-linker flags no other platform's linker accepts. That makes
# Linux the only host this works on — hence the container.
require_linux_host() {
  [ "$(uname -s)" = "Linux" ] || die "This script runs inside the Linux toolchain image.
Run this instead, from the project root:
    bash scripts/build-libnode.sh"
}

# ── Fetch and verify the Node source (§7 — verify what you download) ────────
fetch_node_source() {
  [ -d "$SOURCE_DIR" ] && { log_info "Node $NODE_VERSION source already extracted."; return; }

  log_step "Fetching Node $NODE_VERSION source"
  mkdir -p "$BUILD_DIR"
  local tarball="node-v$NODE_VERSION.tar.xz"
  local base="https://nodejs.org/dist/v$NODE_VERSION"

  [ -f "$BUILD_DIR/$tarball" ] || curl -fsSL -o "$BUILD_DIR/$tarball" "$base/$tarball"
  curl -fsSL -o "$BUILD_DIR/SHASUMS256.txt" "$base/SHASUMS256.txt"

  ( cd "$BUILD_DIR" && grep " $tarball\$" SHASUMS256.txt | shasum -a 256 -c - ) \
    || die "Checksum mismatch on $tarball — refusing to build it."
  log_success "Checksum verified."

  tar -xf "$BUILD_DIR/$tarball" -C "$BUILD_DIR"
  log_success "Extracted to $SOURCE_DIR"
}

# ── Configure ───────────────────────────────────────────────────────────────
# Mirrors node's own android_configure.py, with three deliberate additions:
#   --shared              emit libnode.so rather than a `node` executable
#   --without-npm/corepack  the app ships a prebuilt bundle; nothing installs
#                           packages on the phone
#   --without-node-snapshot the V8 startup snapshot is generated by running a
#                           target binary, which a cross build cannot do
configure_node() {
  local ndk_root toolchain
  ndk_root="$(find_ndk_root)"
  toolchain="$ndk_root/toolchains/llvm/prebuilt/linux-x86_64"
  [ -d "$toolchain" ] || die "NDK toolchain not found at $toolchain"

  if [ "$CLEAN_BUILD" = "1" ]; then
    log_info "--clean: removing previous configure output."
    rm -rf "$SOURCE_DIR/out" "$SOURCE_DIR/config.gypi" "$SOURCE_DIR/config.status"
  elif [ -f "$SOURCE_DIR/config.gypi" ]; then
    log_info "Already configured; skipping (use --clean to redo)."
    return
  fi

  log_step "Configuring Node for android/$DEST_CPU (API $ANDROID_API)"

  export PATH="$toolchain/bin:$PATH"
  export CC="$toolchain/bin/${TOOLCHAIN_PREFIX}${ANDROID_API}-clang"
  export CXX="$toolchain/bin/${TOOLCHAIN_PREFIX}${ANDROID_API}-clang++"
  [ -x "$CC" ] || die "Cross compiler not found: $CC"

  # V8's build produces tools (mksnapshot, torque) that have to RUN on this
  # machine, so they must be compiled for it. gyp picks the host compiler with
  # `CC_host` falling back to `CC` — and `CC` is the Android cross compiler —
  # so without these the host tools are silently built for the phone and the
  # build dies partway through on bionic's missing execinfo.h. Node's own
  # android_configure.py has this gap; naming the host toolchain closes it.
  export CC_host=gcc
  export CXX_host=g++
  export LINK_host=g++
  export AR_host=ar
  command -v "$CC_host" >/dev/null || die "Host compiler '$CC_host' not found in the image."

  export GYP_DEFINES="target_arch=$GYP_ARCH v8_target_arch=$GYP_ARCH \
android_target_arch=$GYP_ARCH host_os=$(uname -s | tr '[:upper:]' '[:lower:]') \
OS=android android_ndk_path=$ndk_root"

  local configure_flags=(
    --dest-cpu="$DEST_CPU"
    --dest-os=android
    --cross-compiling
    --openssl-no-asm
    --shared
    --without-npm
    --without-corepack
    --without-node-snapshot
  )
  # Deliberately NOT --ninja: gyp's ninja generator emits duplicate rules for
  # V8's inspector stamp when host and target toolsets are both in play, which
  # is exactly what a cross build does ("multiple rules generate
  # gen/inspector-generated-output-root/src/js_protocol.stamp"). The make
  # generator handles the dual toolset correctly.

  ( cd "$SOURCE_DIR" && ./configure "${configure_flags[@]}" ) \
    || die "configure failed — see output above."
  log_success "Configured."
}

# ── Build ───────────────────────────────────────────────────────────────────
build_node() {
  log_step "Building libnode.so (this takes 1-2 hours cold)"
  local jobs; jobs="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"

  ( cd "$SOURCE_DIR" && make -j"$jobs" ) || die "build failed — see output above."
  log_success "Build finished."
}

# ── Stage the artifacts the Android app consumes ────────────────────────────
stage_artifacts() {
  log_step "Staging libnode.so and headers"

  local built; built="$(find "$SOURCE_DIR/out/Release" -maxdepth 2 -name 'libnode.so*' -type f | head -1)"
  [ -n "$built" ] || die "Build produced no libnode.so under $SOURCE_DIR/out/Release."

  mkdir -p "$JNI_LIBS_DIR"
  cp "$built" "$JNI_LIBS_DIR/libnode.so"
  log_success "libnode.so -> $JNI_LIBS_DIR ($(du -h "$JNI_LIBS_DIR/libnode.so" | cut -f1))"

  # The JNI bridge includes node.h, which pulls in V8's and libuv's headers.
  rm -rf "$HEADERS_DIR"
  mkdir -p "$HEADERS_DIR/node"
  cp "$SOURCE_DIR/src"/*.h "$HEADERS_DIR/node/"
  cp -R "$SOURCE_DIR/deps/v8/include/." "$HEADERS_DIR/node/"
  cp -R "$SOURCE_DIR/deps/uv/include/." "$HEADERS_DIR/node/"
  log_success "Headers -> $HEADERS_DIR/node"
}

main() {
  log_step "Senderrr libnode.so build — Node $NODE_VERSION, NDK $NDK_VERSION, $ANDROID_ABI"
  require_linux_host
  fetch_node_source
  configure_node
  build_node
  stage_artifacts
  echo
  log_success "Done. The Android app can now link against libnode.so."
}

main "$@"
